/**
 * AUTO-GENERATED by scripts/generate-image-dimensions.ts — do not edit manually.
 * Intrinsic dimensions + WebP paths for CLS prevention and <picture> fallbacks.
 */
export type ImageDimensionEntry = {
  width: number;
  height: number;
  webpPath?: string;
};

export const IMAGE_DIMENSIONS: Record<string, ImageDimensionEntry> = {
  '/blog-aimbot-guide.webp': { width: 1400, height: 788 },
  '/blog-bungie-anticheat.webp': { width: 1400, height: 788 },
  '/blog-esp-guide.webp': { width: 1400, height: 788 },
  '/blog-external-cheat.webp': { width: 1400, height: 788 },
  '/blog-hwid-spoofer.webp': { width: 1400, height: 788 },
  '/blog-loot-esp.webp': { width: 1400, height: 788 },
  '/blog-makima-comparison.webp': { width: 1400, height: 788 },
  '/blog-marathon-cheats-comparison.webp': { width: 1400, height: 788 },
  '/blog-marathon-guide.webp': { width: 1400, height: 788 },
  '/blog-marathon-world.webp': { width: 1400, height: 788 },
  '/blog-novaxware-comparison.webp': { width: 1400, height: 788 },
  '/blog-patch-updates.webp': { width: 1400, height: 788 },
  '/blog-recoil-control.webp': { width: 1400, height: 788 },
  '/blog-sony-bans.webp': { width: 1400, height: 788 },
  '/blog-sternclient-comparison.webp': { width: 1400, height: 788 },
  '/blog-zadeyo-comparison.webp': { width: 1400, height: 788 },
  '/image-44fb6aa2-4123-47aa-ba38-e2a9f0bdaee6.png': { width: 1400, height: 788, webpPath: '/image-44fb6aa2-4123-47aa-ba38-e2a9f0bdaee6.webp' },
  '/image-44fb6aa2-4123-47aa-ba38-e2a9f0bdaee6.webp': { width: 1400, height: 788 },
  '/images/marathon-feature-demo-thumbnail.webp': { width: 1280, height: 720 },
  '/images/marathon-hero-demo-thumbnail.webp': { width: 1280, height: 720 },
  '/marathon-cheats-social-preview.png': { width: 1200, height: 630, webpPath: '/marathon-cheats-social-preview.webp' },
  '/marathon-cheats-social-preview.webp': { width: 1200, height: 630 },
  '/marathon-safety-characters-purple.webp': { width: 1400, height: 788 },
  '/marathon-safety-characters.webp': { width: 1400, height: 788 },
  '/og-google-preview.png': { width: 1024, height: 1024, webpPath: '/og-google-preview.webp' },
  '/og-google-preview.webp': { width: 1024, height: 1024 },
  '/rt-removebg-preview.png': { width: 64, height: 77, webpPath: '/rt-removebg-preview.webp' },
  '/rt-removebg-preview.webp': { width: 64, height: 77 },
};

export function getImageDimensions(path: string): ImageDimensionEntry | undefined {
  const clean = path.split('?')[0] ?? path;
  return IMAGE_DIMENSIONS[clean];
}
