// Generated by scripts/generate-video-metadata.ts — do not edit manually.
export const VIDEO_UPLOAD_DATES_ISO: Record<string, string> = {
  "marathon-hero-demo": "2026-07-21T22:30:08.000Z",
  "marathon-feature-demo": "2026-07-21T22:30:11.000Z"
};

export const VIDEO_UPLOAD_DATES_W3C: Record<string, string> = {
  "marathon-hero-demo": "2026-07-21",
  "marathon-feature-demo": "2026-07-21"
};

export const VIDEO_DURATIONS_SECONDS: Record<string, number> = {
  "marathon-hero-demo": 32,
  "marathon-feature-demo": 20
};
