import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { SITE_VIDEOS } from '../src/content/videos';
import { clampToBuildDate, formatW3cDate } from './sitemap-utils';
import { resolveVideoDurations } from './video-duration';

const buildDate = new Date();

const uploadDates = Object.fromEntries(
  SITE_VIDEOS.map(video => [video.slug, video.publicationDate]),
);

const uploadDateDays = Object.fromEntries(
  SITE_VIDEOS.map(video => {
    const resolved = clampToBuildDate(new Date(video.publicationDate), buildDate);
    return [video.slug, formatW3cDate(resolved)];
  }),
);

const durations = resolveVideoDurations();

const outputPath = join(process.cwd(), 'src', 'content', 'videoMetadata.generated.ts');
const contents = `// Generated by scripts/generate-video-metadata.ts — do not edit manually.
export const VIDEO_UPLOAD_DATES_ISO: Record<string, string> = ${JSON.stringify(uploadDates, null, 2)};

export const VIDEO_UPLOAD_DATES_W3C: Record<string, string> = ${JSON.stringify(uploadDateDays, null, 2)};

export const VIDEO_DURATIONS_SECONDS: Record<string, number> = ${JSON.stringify(durations, null, 2)};
`;

writeFileSync(outputPath, contents, 'utf8');
console.log(`Generated video metadata for ${SITE_VIDEOS.length} videos at ${outputPath}`);
