/**
 * Build-time: reads intrinsic width/height + WebP variant paths from /public.
 * SEO benefit: enables width/height on <img> to prevent CLS without runtime probing.
 */
import { readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import sharp from 'sharp';

const publicDir = join(process.cwd(), 'public');
const outputPath = join(process.cwd(), 'src/content/imageDimensions.ts');

type DimensionEntry = {
  width: number;
  height: number;
  webpPath?: string;
};

const dimensions = new Map<string, DimensionEntry>();

function walk(dir: string) {
  for (const name of readdirSync(dir)) {
    const fullPath = join(dir, name);
    const stats = statSync(fullPath);

    if (stats.isDirectory()) {
      walk(fullPath);
      continue;
    }

    if (!/\.(png|jpe?g|webp|gif)$/i.test(name)) continue;

    const publicPath = `/${relative(publicDir, fullPath).replace(/\\/g, '/')}`;
    dimensions.set(publicPath, { width: 0, height: 0 });
  }
}

walk(publicDir);

for (const [publicPath] of [...dimensions.entries()]) {
  const absolute = join(publicDir, publicPath.slice(1));
  const meta = await sharp(absolute).metadata();

  if (!meta.width || !meta.height) {
    console.warn(`Skipping ${publicPath}: missing dimensions`);
    dimensions.delete(publicPath);
    continue;
  }

  const entry: DimensionEntry = {
    width: meta.width,
    height: meta.height,
  };

  if (/\.(png|jpe?g)$/i.test(publicPath)) {
    const webpPath = publicPath.replace(/\.(png|jpe?g)$/i, '.webp');
    const webpAbsolute = join(publicDir, webpPath.slice(1));
    try {
      statSync(webpAbsolute);
      entry.webpPath = webpPath;
    } catch {
      // WebP variant may be generated in a later build step.
    }
  }

  dimensions.set(publicPath, entry);
}

const sortedEntries = [...dimensions.entries()].sort(([a], [b]) => a.localeCompare(b));

const fileContents = `/**
 * AUTO-GENERATED by scripts/generate-image-dimensions.ts — do not edit manually.
 * Intrinsic dimensions + WebP paths for CLS prevention and <picture> fallbacks.
 */
export type ImageDimensionEntry = {
  width: number;
  height: number;
  webpPath?: string;
};

export const IMAGE_DIMENSIONS: Record<string, ImageDimensionEntry> = {
${sortedEntries
  .map(([path, entry]) => {
    const webp = entry.webpPath ? `, webpPath: '${entry.webpPath}'` : '';
    return `  '${path}': { width: ${entry.width}, height: ${entry.height}${webp} },`;
  })
  .join('\n')}
};

export function getImageDimensions(path: string): ImageDimensionEntry | undefined {
  const clean = path.split('?')[0] ?? path;
  return IMAGE_DIMENSIONS[clean];
}
`;

writeFileSync(outputPath, fileContents, 'utf8');
console.log(`Generated ${sortedEntries.length} image dimension entries → ${relative(process.cwd(), outputPath)}`);
